In [2]:
from pathlib import Path
import os
CUR_PATH = Path('.')
UP_ONE_DIR = Path('..')
DATA_PATH = Path('../COVID-19/')
DAILY_CASES = DATA_PATH / 'archived_data' / 'archived_daily_case_updates'
TIME_SERIES = DATA_PATH / 'archived_data' / 'archived_time_series'
CSSE_PATH = DATA_PATH / 'csse_covid_19_data/'
REPORTS = CSSE_PATH / 'csse_covid_19_daily_reports'
CSSE_TIME_SERIES = CSSE_PATH / 'csse_covid_19_time_series'
import pandas as pd
df=pd.read_csv(DAILY_CASES / '02-13-2020_1000.csv')
df.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Hubei,Mainland China,2020-02-13 14:13:06,48206,1310,3459
1,Guangdong,Mainland China,2020-02-13 13:33:01,1241,2,314
2,Henan,Mainland China,2020-02-13 14:53:02,1169,10,296
3,Zhejiang,Mainland China,2020-02-13 14:13:06,1145,0,360
4,Hunan,Mainland China,2020-02-13 11:53:02,968,2,339

In [11]:
from pathlib import Path
import os
CUR_PATH = Path('.')
UP_ONE_DIR = Path('..')
DATA_PATH = Path('../COVID-19/')
DAILY_CASES = DATA_PATH / 'archived_data' / 'archived_daily_case_updates'
TIME_SERIES = DATA_PATH / 'archived_data' / 'archived_time_series'
CSSE_PATH = DATA_PATH / 'csse_covid_19_data/'
REPORTS = CSSE_PATH / 'csse_covid_19_daily_reports'
CSSE_TIME_SERIES = CSSE_PATH / 'csse_covid_19_time_series'
import pandas as pd
df=pd.read_csv(DAILY_CASES / '01-21-2020_2200.csv')
df.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Suspected
0,Anhui,Mainland China,1/21/2020 10pm,NaN,NaN,NaN,3.0
1,Beijing,Mainland China,1/21/2020 10pm,10.0,NaN,NaN,NaN
2,Chongqing,Mainland China,1/21/2020 10pm,5.0,NaN,NaN,NaN
3,Guangdong,Mainland China,1/21/2020 10pm,17.0,NaN,NaN,4.0
4,Guangxi,Mainland China,1/21/2020 10pm,NaN,NaN,NaN,1.0